import { Router } from "express";
import { healthRouter } from "./health";
import { projectsRouter } from "./projects";
import { authRouter } from "./auth";
import { uploadsRouter } from "./uploads";
import { blogRouter } from "./blog";
import { blogCategoriesRouter } from "./blog-categories";
import { testimonialsRouter } from "./testimonials";
import { siteConfigRouter } from "./site-config";
import { contactRouter } from "./contact";
import { statsRouter } from "./stats";
import { bookingRouter } from "./booking";
import { googleAuthRouter } from "./google-auth";
import { servicesRouter } from "./services";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/projects", projectsRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/uploads", uploadsRouter);
apiRouter.use("/blog", blogRouter);
apiRouter.use("/blog-categories", blogCategoriesRouter);
apiRouter.use("/testimonials", testimonialsRouter);
apiRouter.use("/site-config", siteConfigRouter);
apiRouter.use("/contact", contactRouter);
apiRouter.use("/stats", statsRouter);
apiRouter.use("/booking", bookingRouter);
apiRouter.use("/google-calendar", googleAuthRouter);
apiRouter.use("/services", servicesRouter);
